# auto-generated by brains:diagram — remove this line to protect manual edits
workspace "brains:diagram" "System context for the brains:diagram skill and its renderer pipeline" {

  model {
    dev = person "Developer" "Runs /brains:brains or /brains:diagram"

    brains = softwareSystem "BRAINS Plugin" "Three-phase multi-LLM development workflow" {
      brainsSkill = container "/brains:brains" "Phase 1 — questionnaire, synthesis, ADR"
      diagramSkill = container "/brains:diagram" "Generates Mermaid (.mmd) or Structurizr (.dsl) source and renders .svg"
      setupSkill = container "/brains:setup" "Installs deps; runs and tears down the Kroki pair"
      companion = container "BRAINS! Companion" "Local SSE server with live Mermaid rendering"
    }

    krokiPair = softwareSystem "Local Kroki pair" "yuzutech/kroki gateway + yuzutech/kroki-mermaid companion, on brains-kroki-net" "External"
    mmdc = softwareSystem "mmdc via npx" "Mermaid CLI fallback renderer" "External"
    diagramsDir = softwareSystem "docs/adr/diagrams/" "Canonical source (.mmd, .dsl) + rendered .svg per ADR" "External"
    adrDir = softwareSystem "docs/adr/" "ADRs with ## Diagram section referencing the SVG" "External"
    rendererJson = softwareSystem "~/.config/brains/renderer.json" "kroki_url + runtime + companion metadata" "External"

    dev -> brainsSkill "Invokes phase 1" "/brains:brains"
    dev -> diagramSkill "Standalone diagram generation" "/brains:diagram"
    dev -> setupSkill "Enable or disable Kroki" "--with-kroki / --without-kroki"
    dev -> companion "Views mockups, ADRs, diagrams" "http://127.0.0.1:<port>"

    brainsSkill -> diagramSkill "Auto-trigger at ADR write (step 8)" "skill dispatch"
    brainsSkill -> adrDir "Writes ADR with ## Diagram section" "Write tool"

    diagramSkill -> rendererJson "Reads kroki_url for renderer detection" "file read"
    diagramSkill -> krokiPair "POST /mermaid/svg or /structurizr/svg" "HTTP (localhost only)"
    diagramSkill -> mmdc "Fallback for Mermaid types only" "npx subprocess"
    diagramSkill -> diagramsDir "Writes source first, then SVG" "Write tool"

    setupSkill -> krokiPair "Runs gateway + mermaid companion on brains-kroki-net" "podman / docker"
    setupSkill -> rendererJson "Atomic write or cleanup" "file write"

    companion -> krokiPair "Live Mermaid block rendering in fragments" "HTTP"

    adrDir -> diagramsDir "References SVG via relative path" "![](diagrams/...svg)"
  }

  views {
    systemContext brains "SystemContext" {
      include *
      autoLayout lr
    }

    container brains "Containers" {
      include *
      autoLayout lr
    }

    styles {
      element "External" {
        background #999999
        color #ffffff
      }
      element "Person" {
        shape person
      }
    }

    theme default
  }
}
