# auto-generated by brains:diagram — remove this line to protect manual edits
workspace "BRAINS" "System context for the BRAINS plugin" {

  model {
    dev = person "Developer" "Runs /brains:* commands in Claude Code"

    brains = softwareSystem "BRAINS Plugin" "Three-phase multi-LLM development workflow" {
      orch = container "Orchestrator" "Claude Code session running /brains:brains, /brains:map, /brains:implement"
      teammate = container "Teammate" "Per-phase Claude Code spawned via tmux or agent-teams"
      companion = container "BRAINS! Companion" "Local SSE server serving mockups, ADR view, diagrams"
      diagram = container "brains:diagram" "Generates Mermaid (.mmd) or Structurizr (.dsl) source and renders .svg"
    }

    starchamber = softwareSystem "star-chamber" "Multi-LLM council invoked via uvx" "External"
    beads = softwareSystem "beads" "Task tracker (Dolt-backed)" "External"
    kroki = softwareSystem "Local Kroki" "yuzutech/kroki container bound to 127.0.0.1" "External"
    mmdc = softwareSystem "mmdc via npx" "Mermaid CLI fallback renderer" "External"

    dev -> orch "Invokes skills" "CLI"
    dev -> companion "Views mockups and ADRs" "http://127.0.0.1:<port>"
    orch -> teammate "Spawns per plan-phase" "tmux / agent-teams"
    orch -> starchamber "Review or debate" "uvx"
    teammate -> beads "Grooms, claims, closes tasks" "bd CLI"
    orch -> diagram "Auto-trigger during ADR write" "skill dispatch"
    diagram -> kroki "POST /mermaid/svg or /structurizr/svg" "HTTP (localhost only)"
    diagram -> mmdc "Fallback render for Mermaid types" "npx subprocess"
  }

  views {
    systemContext brains "SystemContext" {
      include *
      autoLayout lr
    }

    container brains "Containers" {
      include *
      autoLayout lr
    }

    styles {
      element "External" {
        background #999999
        color #ffffff
      }
      element "Person" {
        shape person
      }
    }

    theme default
  }
}
